runtime: java17
service: datastore
entrypoint: java -jar datastore-all.jar

automatic_scaling:
  min_idle_instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto